#!/bin/bash
exec 2> >(tee -a errors2.log >&2)
# Generate fstab
echo "Generating fstab..."
genfstab -U /mnt >> /mnt/etc/fstab
cat /mnt/etc/fstab

# System configuration via arch-chroot
echo "Configuring system via arch-chroot..."
arch-chroot /mnt <<EOF

# Uncomment lines for ru_RU and en_US locales
echo "Uncommenting ru_RU.UTF-8 and en_US.UTF-8 locales in /etc/locale.gen..."
sed -i 's/#ru_RU.UTF-8 UTF-8/ru_RU.UTF-8 UTF-8/' /etc/locale.gen
sed -i 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen

# Generate locales
echo "Generating locales..."
locale-gen

# Configure time
echo "Configuring time..."
ln -sf /usr/share/zoneinfo/Europe/Moscow /etc/localtime
hwclock --systohc

# Set hostname
echo "Setting hostname..."
echo "arch" > /etc/hostname

# Set root password
echo "root:$root_password" | chpasswd

# Add new user and configure permissions
echo "Adding new user 'user' and configuring permissions..."
useradd -m -G wheel,users,video -s /bin/bash user
echo "user:$user_password" | chpasswd

# Enable dhcpcd and iwd services
echo "Enabling dhcpcd and iwd services..."
systemctl enable dhcpcd
systemctl enable iwd.service

echo "Configuring kernel"
micro /etc/mkinitcpio.conf

echo "Rebuilding kernel"
mkinitcpio -p linux

# Install bootloader
echo "Installing bootloader"
bootctl install --path=/boot

# Go to bootloader directory and clear loader.conf if anything exists
echo "Going to bootloader directory and clearing loader.conf if needed"
cd /boot/loader

# Edit loader.conf
echo "Editing loader.conf"
echo "timeout 3" >> /boot/loader/loader.conf
echo "default arch" >> /boot/loader/loader.conf

#micro /boot/loader/loader.conf

# Go to boot configurations directory and create arch.conf
#---------------------------------------------
cd /boot/loader/entries
echo "title Arch Linux" > /boot/loader/entries/arch.conf
echo "linux /vmlinuz-linux" >> /boot/loader/entries/arch.conf
echo "initrd /initramfs-linux.img" >> /boot/loader/entries/arch.conf
# Get UUID for /dev/nvme0n1p2 to properly specify in boot options
UUID=\$(blkid /dev/nvme0n1p2 -o value -s UUID)

# Insert encryption options
echo "options rw cryptdevice=UUID=\$UUID:main root=/dev/mapper/main-root" >> /boot/loader/entries/arch.conf

#micro /boot/loader/entries/arch.conf

sudo EDITOR=micro visudo

EOF
umount -R /mnt
echo "Process completed."
